[versions]
build-tools = "7.3.1"
kotlin-plugin = "1.7.20"
google-services = "4.3.14"

huawei-agcp = "1.6.5.300"
firebase-crashlytics = "2.9.2"
hilt-android-plugin = "2.44"

navigation-safe-args-plugin = "2.3.5"
jacoco = "0.8.8"

[libraries]
build-tools = { module = "com.android.tools.build:gradle", version.ref = "build-tools" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
huawei-agcp = { module = "com.huawei.agconnect:agcp", version.ref = "huawei-agcp" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics" }
navigation-safe-args-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-plugin" }
jacoco-core = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android-plugin" }